# Generated by Django 4.2.9 on 2024-01-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview',
            name='img',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='preview',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
