# Generated by Django 4.2.9 on 2024-01-22 06:32

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_preview_img_alter_preview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='title_tsvector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
