# Generated by Django 4.2.9 on 2024-01-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_preview_title_tsvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='kind',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='preview',
            index=models.Index(fields=['kind'], name='app_preview_kind_40ad4d_idx'),
        ),
    ]
